/**
 * The technique catalog registry.
 *
 * Pure, like the gate registry, and for the same reason: lookups must be
 * deterministic and available anywhere without a filesystem. The data arrives as a
 * **module import**, not a file read — importing JSON is resolution, not I/O, which is
 * what lets 172 records live inside Core without breaking ADR-0005.
 *
 * `techniques.json` is generated by `npm run import:catalog` and must not be edited by
 * hand. That step is where the frozen source becomes the project's own data: eight
 * citation titles are wrong in `sources/`, verified against arXiv, and are corrected
 * at the boundary rather than in the frozen record. `npm run check:catalog` fails if
 * the committed file is not what the source plus corrections currently produce.
 */

import data from "./techniques.json" with { type: "json" };
import type { TechniqueRecord, TechniqueCategory } from "../../../contracts/index.js";

const TECHNIQUES: readonly TechniqueRecord[] = Object.freeze(
  (data as { techniques: TechniqueRecord[] }).techniques,
);

/** Indexed once at module load. Registration is data, not effect. */
const BY_ID = new Map(TECHNIQUES.map((t) => [t.id, t]));
const BY_ALIAS = new Map<string, TechniqueRecord>();
for (const t of TECHNIQUES) {
  for (const alias of t.aliases) {
    // First registration wins, so an alias collision cannot silently reassign a name.
    if (!BY_ALIAS.has(alias)) BY_ALIAS.set(alias, t);
  }
}

export const TECHNIQUE_COUNT = TECHNIQUES.length;

/** Provenance of the imported data — which source, which corrections. */
export const CATALOG_PROVENANCE = (data as { _provenance: Record<string, unknown> })._provenance;

/** Every record, in the frozen source's order. Stable across runs. */
export function listTechniques(): readonly TechniqueRecord[] {
  return TECHNIQUES;
}

/** Look up by id, then by alias. Returns undefined rather than throwing — a miss is an ordinary answer. */
export function getTechnique(idOrAlias: string): TechniqueRecord | undefined {
  return BY_ID.get(idOrAlias) ?? BY_ALIAS.get(idOrAlias);
}

export function techniquesInCategory(category: TechniqueCategory): readonly TechniqueRecord[] {
  return TECHNIQUES.filter((t) => t.category === category);
}

/**
 * Records whose claims a deterministic checker could settle, as opposed to those
 * needing a judge or unverifiable from text alone. The distinction is the catalog's,
 * and it is the one that decides whether a technique can back a gate.
 */
export function verifierCheckable(): readonly TechniqueRecord[] {
  return TECHNIQUES.filter((t) => t.verification_status === "verifier-checkable");
}
